version: '3.8'

services:
  # Service 1: MinIO (จำลอง Cloud Storage)
  minio:
    image: minio/minio
    container_name: local-datalake
    ports:
      - "9000:9000"   # Port สำหรับ API
      - "9001:9001"   # Port สำหรับหน้าเว็บ Console
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data # Map ข้อมูลมาเก็บในเครื่องเรา

  # Service 2: Python Script ดึงหุ้น
  ingestor:
    build: .
    container_name: stock-ingestor
    depends_on:
      - minio # รอให้ MinIO รันเสร็จก่อนค่อยเริ่มทำงาน
    volumes:
      - ./data:/app/data
    environment:
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "password"
      BUCKET_NAME: "stock-data"