version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: local-datalake
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  ingestor:
    build: .
    container_name: stock-ingestor
    depends_on:
      - minio
    volumes:
      - ./data:/app/data
    environment:
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "password"
      BUCKET_NAME: "stock-data"
    # command: ["python", "ingest_data.py"] 


  transformer:
    build: .
    container_name: stock-transformer
    depends_on:
      - minio
      - ingestor 
    environment:
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "password"
    command: ["python", "transform_data.py"]